name: Validar merge por usuario específico

on:
  pull_request_review:
    types:
      - submitted

jobs:
  check-approver:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el revisor del PR
        run: |
          # Obtener el revisor del pull request
          REVIEWER=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews | jq -r '.[0].user.login')
          
          # Verificar si el revisor es "abdon"
          if [ "$REVIEWER" != "agonzalezo03" ]; then
            echo "El revisor que aprobó el PR no es Abdon. El revisor fue $REVIEWER."
            exit 1
          fi
          echo "El revisor que aprobó el PR es Abdon. Continuando..."
